const columns = [
  { name: "Kode", uid: "kode" },
  { name: "RT", uid: "rt" },
  { name: "RW", uid: "rw" },
  { name: "Dusun", uid: "dusun" },
  { name: "Jumlah Usaha", uid: "jml_unit_usaha_klengkeng" },
  { name: "Aksi", uid: "aksi" },
];

const daftarRt = [
    {
      kode: "3515009001001",
      rt: "001",
      rw: "001",
      dusun: "Dusun A",
      jml_ruta: 16,
      jml_umkm: 7,
      jml_umkm_tetap: 6,
      jml_umkm_nontetap: 1,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 2,
      jml_umkm_kbli_i: 0,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001002",
      rt: "002",
      rw: "001",
      dusun: "Dusun B",
      jml_ruta: 18,
      jml_umkm: 7,
      jml_umkm_tetap: 5,
      jml_umkm_nontetap: 2,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 1,
      jml_umkm_kbli_i: 1,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001003",
      rt: "003",
      rw: "001",
      dusun: "Dusun C",
      jml_ruta: 17,
      jml_umkm: 7,
      jml_umkm_tetap: 5,
      jml_umkm_nontetap: 2,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 1,
      jml_umkm_kbli_i: 1,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001004",
      rt: "004",
      rw: "001",
      dusun: "Dusun D",
      jml_ruta: 19,
      jml_umkm: 7,
      jml_umkm_tetap: 6,
      jml_umkm_nontetap: 1,
      jml_umkm_kbli_a: 1,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 2,
      jml_umkm_kbli_i: 0,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001005",
      rt: "005",
      rw: "001",
      dusun: "Dusun E",
      jml_ruta: 18,
      jml_umkm: 7,
      jml_umkm_tetap: 6,
      jml_umkm_nontetap: 1,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 2,
      jml_umkm_kbli_i: 0,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001006",
      rt: "006",
      rw: "001",
      dusun: "Dusun F",
      jml_ruta: 16,
      jml_umkm: 7,
      jml_umkm_tetap: 6,
      jml_umkm_nontetap: 1,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 2,
      jml_umkm_kbli_i: 0,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001007",
      rt: "007",
      rw: "001",
      dusun: "Dusun G",
      jml_ruta: 17,
      jml_umkm: 7,
      jml_umkm_tetap: 5,
      jml_umkm_nontetap: 2,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 1,
      jml_umkm_kbli_i: 1,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001008",
      rt: "008",
      rw: "001",
      dusun: "Dusun H",
      jml_ruta: 15,
      jml_umkm: 7,
      jml_umkm_tetap: 5,
      jml_umkm_nontetap: 2,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 1,
      jml_umkm_kbli_i: 1,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001009",
      rt: "009",
      rw: "001",
      dusun: "Dusun I",
      jml_ruta: 16,
      jml_umkm: 7,
      jml_umkm_tetap: 6,
      jml_umkm_nontetap: 1,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 2,
      jml_umkm_kbli_i: 0,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001010",
      rt: "010",
      rw: "001",
      dusun: "Dusun J",
      jml_ruta: 17,
      jml_umkm: 7,
      jml_umkm_tetap: 5,
      jml_umkm_nontetap: 2,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 1,
      jml_umkm_kbli_i: 1,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001011",
      rt: "011",
      rw: "001",
      dusun: "Dusun K",
      jml_ruta: 18,
      jml_umkm: 7,
      jml_umkm_tetap: 5,
      jml_umkm_nontetap: 2,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 1,
      jml_umkm_kbli_i: 1,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001012",
      rt: "012",
      rw: "001",
      dusun: "Dusun L",
      jml_ruta: 16,
      jml_umkm: 7,
      jml_umkm_tetap: 6,
      jml_umkm_nontetap: 1,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 2,
      jml_umkm_kbli_i: 0,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001013",
      rt: "013",
      rw: "001",
      dusun: "Dusun M",
      jml_ruta: 16,
      jml_umkm: 7,
      jml_umkm_tetap: 6,
      jml_umkm_nontetap: 1,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 2,
      jml_umkm_kbli_i: 0,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001014",
      rt: "014",
      rw: "001",
      dusun: "Dusun N",
      jml_ruta: 17,
      jml_umkm: 7,
      jml_umkm_tetap: 5,
      jml_umkm_nontetap: 2,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 1,
      jml_umkm_kbli_i: 1,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    },
    {
      kode: "3515009001015",
      rt: "015",
      rw: "001",
      dusun: "Dusun O",
      jml_ruta: 18,
      jml_umkm: 7,
      jml_umkm_tetap: 5,
      jml_umkm_nontetap: 2,
      jml_umkm_kbli_a: 2,
      jml_umkm_kbli_b: 0,
      jml_umkm_kbli_c: 1,
      jml_umkm_kbli_d: 0,
      jml_umkm_kbli_e: 0,
      jml_umkm_kbli_f: 1,
      jml_umkm_kbli_g: 0,
      jml_umkm_kbli_h: 1,
      jml_umkm_kbli_i: 1,
      jml_umkm_kbli_j: 1,
      jml_umkm_kbli_k: 0,
      jml_umkm_kbli_l: 0,
      jml_umkm_kbli_m: 0,
      jml_umkm_kbli_n: 0,
      jml_umkm_kbli_o: 0,
      jml_umkm_kbli_p: 0,
      jml_umkm_kbli_q: 0,
      jml_umkm_kbli_r: 0,
      jml_umkm_kbli_s: 0,
      jml_umkm_kbli_t: 0,
      jml_umkm_kbli_u: 0
    }
  ];

export { columns, daftarRt };
