export const dataLabels = [
  { key: "jml_ruta", label: "Keluarga" },
  { key: "jml_umkm", label: "UMKM" },
  { key: "jml_umkm_kbli_a", label: "UMKM Kategori A" },
  { key: "jml_umkm_kbli_b", label: "UMKM Kategori B" },
  { key: "jml_umkm_kbli_c", label: "UMKM Kategori C" },
  { key: "jml_umkm_kbli_d", label: "UMKM Kategori D" },
  { key: "jml_umkm_kbli_e", label: "UMKM Kategori E" },
  { key: "jml_umkm_kbli_f", label: "UMKM Kategori F" },
  { key: "jml_umkm_kbli_g", label: "UMKM Kategori G" },
  { key: "jml_umkm_kbli_h", label: "UMKM Kategori H" },
  { key: "jml_umkm_kbli_i", label: "UMKM Kategori I" },
  { key: "jml_umkm_kbli_j", label: "UMKM Kategori J" },
  { key: "jml_umkm_kbli_k", label: "UMKM Kategori K" },
  { key: "jml_umkm_kbli_l", label: "UMKM Kategori L" },
  { key: "jml_umkm_kbli_m", label: "UMKM Kategori M" },
  { key: "jml_umkm_kbli_n", label: "UMKM Kategori N" },
  { key: "jml_umkm_kbli_o", label: "UMKM Kategori O" },
  { key: "jml_umkm_kbli_p", label: "UMKM Kategori P" },
  { key: "jml_umkm_kbli_q", label: "UMKM Kategori Q" },
  { key: "jml_umkm_kbli_r", label: "UMKM Kategori R" },
  { key: "jml_umkm_kbli_s", label: "UMKM Kategori S" },
  { key: "jml_umkm_kbli_t", label: "UMKM Kategori T" },
  { key: "jml_umkm_kbli_u", label: "UMKM Kategori U" },
  {
    key: "jml_umkm_lokasi_bangunan_khusus_usaha",
    label: "UMKM Bangunan Khusus Usaha",
  },
  {
    key: "jml_umkm_lokasi_bangunan_campuran",
    label: "UMKM Bangunan Campuran",
  },
  { key: "jml_umkm_lokasi_kaki_lima", label: "UMKM Kaki Lima" },
  { key: "jml_umkm_lokasi_keliling", label: "UMKM Keliling" },
  {
    key: "jml_umkm_lokasi_didalam_bangunan_tempat_tinggal_online",
    label: "UMKM di Dalam Bangunan Tempat Tinggal atau Online",
  },
  {
    key: "jml_umkm_bentuk_pt_persero_sejenisnya",
    label: "UMKM PT/Persero/Sejenisnya",
  },
  {
    key: "jml_umkm_bentuk_ijin_desa_ijin_lainnya",
    label: "UMKM Ijin Desa/Ijin Lainnya",
  },
  {
    key: "jml_umkm_bentuk_tidak_berbadan_hukum",
    label: "UMKM Tidak Berbadan Hukum",
  },
  { key: "jml_umkm_skala_usaha_mikro", label: "UMKM Mikro" },
  { key: "jml_umkm_skala_usaha_kecil", label: "UMKM Kecil" },
  { key: "jml_umkm_skala_usaha_menengah", label: "UMKM Menengah" },
];

export const dataLabelSimoketawang = [
  { key: "jml_unit_usaha_klengkeng", label: "Potensi Kelengkeng" },
  { key: "jml_unit_usaha_klengkeng_pupuk_organik", label: "Potensi Kelengkeng Pupuk Organik" },
  { key: "jml_unit_usaha_klengkeng_pupuk_anorganik", label: "Potensi Kelengkeng Pupuk Anorganik" },
  { key: "jml_unit_usaha_klengkeng_tidak_ada_pupuk", label: "Potensi Kelengkeng Tidak Ada Pupuk" },
  { key: "jml_unit_usaha_klengkeng_kopi_biji_klengkeng", label: "Potensi Kelengkeng Kopi Biji Kelengkeng" },
  { key: "jml_unit_usaha_klengkeng_kerajinan_tangan", label: "Potensi Kelengkeng Kerajinan Tangan" },
  { key: "jml_unit_usaha_klengkeng_batik_ecoprint", label: "Potensi Kelengkeng Batik Ecoprint" },
  { key: "jml_unit_usaha_klengkeng_minuman", label: "Potensi Kelengkeng Minuman" },
  { key: "jml_unit_usaha_klengkeng_makanan", label: "Potensi Kelengkeng Makanan" },
  { key: "jml_unit_usaha_klengkeng_tidak_dimanfaatkan", label: "Potensi Kelengkeng Tidak Ada Pemanfaatan" }, // Menambahkan yang tidak ada sebelumnya
  { key: "jml_pohon", label: "Pohon Kelengkeng" },
  { key: "jml_pohon_new_crystal", label: "Pohon Kelengkeng New Crystal" },
  { key: "jml_pohon_pingpong", label: "Pohon Kelengkeng Pingpong" },
  { key: "jml_pohon_metalada", label: "Pohon Kelengkeng Metalada" },
  { key: "jml_pohon_diamond_river", label: "Pohon Kelengkeng Diamond River" },
  { key: "jml_pohon_merah", label: "Pohon Kelengkeng Merah" },
  { key: "jml_pohon_blm_berproduksi", label: "Pohon Kelengkeng Belum Berproduksi" },
  { key: "jml_pohon_sdh_berproduksi", label: "Pohon Kelengkeng Sudah Berproduksi" },
  { key: "volume_produksi", label: "Volume Produksi Agustus 2023-Juli 2024 (kg)" }, // Menambahkan yang tidak ada sebelumnya
];

export const dataLabelGrogol = [
  { key: "total_usaha_sayuran", label: "Total Usaha Sayuran" },
  { key: "total_tanaman_kangkung", label: "Total Tanaman Kangkung" },
  { key: "total_tanaman_bayam", label: "Total Tanaman Bayam" },
  { key: "total_tanaman_sawi", label: "Total Tanaman Sawi" },
  { key: "total_rata2_luas_tanam_kangkung", label: "Total Luas Tanam Kangkung (m²)" },
  { key: "total_rata2_luas_tanam_bayam", label: "Total Luas Tanam Bayam (m²)" },
  { key: "total_rata2_luas_tanam_sawi", label: "Total Luas Tanam Sawi (m²)" },
  { key: "total_rata2_luas_panen_kangkung", label: "Total Luas Panen Kangkung (m²)" },
  { key: "total_rata2_luas_panen_bayam", label: "Total Luas Panen Bayam (m²)" },
  { key: "total_rata2_luas_panen_sawi", label: "Total Luas Panen Sawi (m²)" },
  { key: "total_rata2_volume_produksi_kangkung", label: "Total Volume Produksi Kangkung (kg)" },
  { key: "total_rata2_volume_produksi_bayam", label: "Total Volume Produksi Bayam (kg)" },
  { key: "total_rata2_volume_produksi_sawi", label: "Total Volume Produksi Sawi (kg)" },
  { key: "total_rata2_nilai_produksi_kangkung", label: "Total Nilai Produksi Kangkung (000 Rp)" },
  { key: "total_rata2_nilai_produksi_bayam", label: "Total Nilai Produksi Bayam (000 Rp)" },
  { key: "total_rata2_nilai_produksi_sawi", label: "Total Nilai Produksi Sawi (000 Rp)" },
  { key: "total_tanaman_kangkung_dijual_sendiri", label: "Total Tanaman Kangkung Dijual Sendiri" },
  { key: "total_tanaman_bayam_dijual_sendiri", label: "Total Tanaman Bayam Dijual Sendiri" },
  { key: "total_tanaman_sawi_dijual_sendiri", label: "Total Tanaman Sawi Dijual Sendiri" },
  { key: "total_tanaman_kangkung_dijual_ke_tengkulak", label: "Total Tanaman Kangkung Dijual ke Tengkulak" },
  { key: "total_tanaman_bayam_dijual_ke_tengkulak", label: "Total Tanaman Bayam Dijual ke Tengkulak" },
  { key: "total_tanaman_sawi_dijual_ke_tengkulak", label: "Total Tanaman Sawi Dijual ke Tengkulak" },
];
