export const dataLabels = [
  { key: "jml_ruta", label: "Keluarga" },
  { key: "jml_umkm", label: "UMKM" },
  { key: "jml_umkm_kbli_a", label: "UMKM Kategori A" },
  { key: "jml_umkm_kbli_b", label: "UMKM Kategori B" },
  { key: "jml_umkm_kbli_c", label: "UMKM Kategori C" },
  { key: "jml_umkm_kbli_d", label: "UMKM Kategori D" },
  { key: "jml_umkm_kbli_e", label: "UMKM Kategori E" },
  { key: "jml_umkm_kbli_f", label: "UMKM Kategori F" },
  { key: "jml_umkm_kbli_g", label: "UMKM Kategori G" },
  { key: "jml_umkm_kbli_h", label: "UMKM Kategori H" },
  { key: "jml_umkm_kbli_i", label: "UMKM Kategori I" },
  { key: "jml_umkm_kbli_j", label: "UMKM Kategori J" },
  { key: "jml_umkm_kbli_k", label: "UMKM Kategori K" },
  { key: "jml_umkm_kbli_l", label: "UMKM Kategori L" },
  { key: "jml_umkm_kbli_m", label: "UMKM Kategori M" },
  { key: "jml_umkm_kbli_n", label: "UMKM Kategori N" },
  { key: "jml_umkm_kbli_o", label: "UMKM Kategori O" },
  { key: "jml_umkm_kbli_p", label: "UMKM Kategori P" },
  { key: "jml_umkm_kbli_q", label: "UMKM Kategori Q" },
  { key: "jml_umkm_kbli_r", label: "UMKM Kategori R" },
  { key: "jml_umkm_kbli_s", label: "UMKM Kategori S" },
  { key: "jml_umkm_kbli_t", label: "UMKM Kategori T" },
  { key: "jml_umkm_kbli_u", label: "UMKM Kategori U" },
  {
    key: "jml_umkm_lokasi_bangunan_khusus_usaha",
    label: "UMKM Bangunan Khusus Usaha",
  },
  {
    key: "jml_umkm_lokasi_bangunan_campuran",
    label: "UMKM Bangunan Campuran",
  },
  { key: "jml_umkm_lokasi_kaki_lima", label: "UMKM Kaki Lima" },
  { key: "jml_umkm_lokasi_keliling", label: "UMKM Keliling" },
  {
    key: "jml_umkm_lokasi_didalam_bangunan_tempat_tinggal_online",
    label: "UMKM di Dalam Bangunan Tempat Tinggal atau Online",
  },
  {
    key: "jml_umkm_bentuk_pt_persero_sejenisnya",
    label: "UMKM PT/Persero/Sejenisnya",
  },
  {
    key: "jml_umkm_bentuk_ijin_desa_ijin_lainnya",
    label: "UMKM Ijin Desa/Ijin Lainnya",
  },
  {
    key: "jml_umkm_bentuk_tidak_berbadan_hukum",
    label: "UMKM Tidak Berbadan Hukum",
  },
  { key: "jml_umkm_skala_usaha_mikro", label: "UMKM Mikro" },
  { key: "jml_umkm_skala_usaha_kecil", label: "UMKM Kecil" },
  { key: "jml_umkm_skala_usaha_menengah", label: "UMKM Menengah" },
];

export const dataLabelSimoketawang = [
  { key: "jml_unit_usaha_klengkeng", label: "Unit Usaha Klengkeng" },
  { key: "jml_unit_usaha_klengkeng_pupuk_organik", label: "Unit Usaha Klengkeng Pupuk Organik" },
  { key: "jml_unit_usaha_klengkeng_pupuk_anorganik", label: "Unit Usaha Klengkeng Pupuk Anorganik" },
  { key: "jml_unit_usaha_klengkeng_tidak_ada_pupuk", label: "Unit Usaha Klengkeng Tidak Ada Pupuk" },
  { key: "jml_unit_usaha_klengkeng_kopi_biji_klengkeng", label: "Unit Usaha Klengkeng Kopi Biji Klengkeng" },
  { key: "jml_unit_usaha_klengkeng_kerajinan_tangan", label: "Unit Usaha Klengkeng Kerajinan Tangan" },
  { key: "jml_unit_usaha_klengkeng_batik_ecoprint", label: "Unit Usaha Klengkeng Batik Ecoprint" },
  { key: "jml_unit_usaha_klengkeng_minuman", label: "Unit Usaha Klengkeng Minuman" },
  { key: "jml_unit_usaha_klengkeng_makanan", label: "Unit Usaha Klengkeng Makanan" },
  { key: "jml_unit_usaha_klengkeng_tidak_dimanfaatkan", label: "Unit Usaha Klengkeng Tidak Ada Pemanfaatan" }, // Menambahkan yang tidak ada sebelumnya
  { key: "jml_pohon", label: "Pohon Klengkeng" },
  { key: "jml_pohon_new_crystal", label: "Pohon Klengkeng New Crystal" },
  { key: "jml_pohon_pingpong", label: "Pohon Klengkeng Pingpong" },
  { key: "jml_pohon_metalada", label: "Pohon Klengkeng Metalada" },
  { key: "jml_pohon_diamond_river", label: "Pohon Klengkeng Diamond River" },
  { key: "jml_pohon_merah", label: "Pohon Klengkeng Merah" },
  { key: "jml_pohon_blm_berproduksi", label: "Pohon Klengkeng Belum Berproduksi" },
  { key: "jml_pohon_sdh_berproduksi", label: "Pohon Klengkeng Sudah Berproduksi" },
  { key: "volume_produksi", label: "Volume Produksi Agustus 2023-Juli 2024 (Kg)" }, // Menambahkan yang tidak ada sebelumnya
];
